config/routes.rb
Holarse::Application.routes.draw do

  get "impressum" => "static_pages#imprint", as: :imprint
  get "intro" => "static_pages#intro", as: :introduction
  get "markdownhelp" => "static_pages#markdownhelp", as: :markdownhelp
  get "newcontent" => "static_pages#newcontent", as: :newcontent

  # api
  get "holarse/api/autolinkable" # erzeugt die internen links auf artikel
  get "holarse/api/discount_count" # zaehlt die rabattaktionen
  post "holarse/api/markup_preview" # ermoeglicht die vorschau von markdown-seiten
  get "holarse/api/minecrafters" # die whitegelisteten minecraft-user
  get "holarse/api/site_statistics" # die holarse-statistik
  get "holarse/api/taglist" # die tagliste je kategorie
  get "holarse/api/mumble" # der mumble-user count
  post "holarse/api/grab_title" # der seitentitel
  get "holarse/api/inbox_count"

  # holarse-services-seiten
  get "holarse/service/index", as: :holarse_service
  get "holarse/service/mumble", as: :holarse_service_mumble
  get "holarse/service/jabber", as: :holarse_service_jabber
  get "holarse/service/gameserver", as: :holarse_service_gameserver
  get "holarse/service/communities", as: :holarse_service_communities

  # die angebotsaktionen
  resources :discount_events do
    resources :comments
  end

  resources :inboxes

  # die suche
  get "search/suggest" => "search#suggest"
  match "search/(:q)" => "search#show", as: :search, via: [:get, :post]
  get "search/tags/:q" => "search#tags", as: :searchtag

  # die entwuerfe
  resources :drafts

  # webseiten resourcen
  resources :users
  resources :news do
    resources :comments
    resources :videos
    resources :history
    resources :news_updates
  end

  resources :articles do
    resources :comments
    resources :videos
    resources :history
  end

  # abwaertskompatibilitaet
  get "wiki/:name", to: redirect("/articles/%{name}")

  # login und sessionverwaltung
  get 'users/new', as: :register
  resource :session, only: [:new, :create, :destroy]
  get 'session/login' => 'sessions#new', as: :login
  get 'session/logout' => 'sessions#destroy', as: :logout

  # einzelseiten
  get "welcome/index"
    
  # shortcuts
  get "videos" => "media#videos"

  # redirects
  get "/redirect/twitter" => redirect("https://twitter.com/#!/holarse"), as: :twitter

  get "/redirect/youtube/:channel" => redirect("https://www.youtube.com/user/%{channel}"), as: :youtube_channel

  get '/redirect/osm/:city' => redirect("http://nominatim.openstreetmap.org/search.php?q=%{city}"), as: :osm

  get '/version/:commitid' => redirect("https://github.com/commel/holarse/commit/%{commitid}"), as: :version
  get '/github'	=> redirect("https://github.com/commel/holarse"), as: :github 
  get '/yt/holarse' => redirect("https://www.youtube.com/user/holarse"), as: :youtube

  # root
  root :to => "welcome#index"
  
end

app/controllers/static_pages_controller.rb
#encoding: utf-8
class StaticPagesController < ApplicationController

  layout "doku", only: [:markdownhelp]

  def imprint
    add_breadcrumb "Impressum"
  end

  def intro
    add_breadcrumb "Einführung"
  end

  def markdownhelp
    add_breadcrumb "Markdown-Hilfe"
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/imprint.html.haml
.container
  %p
    Holarse ist ein Gemeinschaftsprojekt von vielen Freiwilligen. Es wurde initiiert von:

  %address
    %strong
      Bernd Ritter
      %br
    Roggenkamp 32
    %br
    27751 Delmenhorst
    %br
    %abbr{:title => "Telefon"}
      T:
    04221 2985986
    %br
    %abbr{:title => "Email"}
      E:
    contact at holarse dash linuxgaming dot de

app/views/static_pages/intro.html.haml
.container
  .row.margin-bottom-30
    .col-md-6.md-margin-bottom-40
      %p
        Eine Einführung zu Holarse - Spielen unter Linux
      %p
        Ein Holarse. Ist das wildlebend? Kann man das essen? Wenn ja, wieviele?

app/views/static_pages/markdownhelp.html.haml
.page-header
  %h1
    Markdown-Dokumentation
    %small
      Kurz&uuml;bersicht &uuml;ber die Befehle

  %p
    = button_to "Zurück", :back, class: "btn-u btn-primary"

#md-help-render

#md-help-source.hidden
  :preserve
     
    **Grundsätzlich sei gesagt, dass die Steuerelemente oft nur wirken, wenn vor dem Element eine Leerzeile gesetzt wurde. Des Weiteren werden Blöcke immer mit mindestens gleicher Anzahl an Zeichen beendet, wie angefangen.**
    
    ### Inhaltsverzeichnis
    1. [Überschriften](#berschriften)
    2. [Listen](#listen)
        1. [Aufzählungsliste](#aufzhlungsliste)
        2. [Listenpunkte](#listenpunkte)
        3. [Definitionsliste](#definitionsliste)
    3. [Code](#code)
        1. [Code im Text](#code-im-text)
        2. [Code-Blöcke](#code-blcke)
    4. [Links](#links)
    5. [Bilder](#bilder)
    6. [Zitate](#zitate)
    6. [Formatierungen](#formatierungen)
        1. [Kursiv](#kursiv)
        2. [Fett](#fett)
    7. [Linien](#linien)
    8. Anhang
        1. [Weiterführende Informationen](#weiterfhrende-informationen)
        2. [Code-Sammlung](#code-sammlung)
            1. [Listen-Code](#listen-code)
            2. [Code-Code](#code-code)

    ### Überschriften
    Eine Überschrift fängt mit mindestens einem [Doppelkreuz][1] (`#`) an. Tiefere Ebenen werden mit mehreren [Doppelkreuzen][1] realisiert. Wir starten in unseren Artikeln mit der 3. Ebene - diese Überschrift fängt bei Holarse also so an: `### Überschriften`

    ### Listen
    Listen können entweder aus Zahlen mit abschließendem Punkt, oder aus den Zeichen `-`, `*` oder `+` bestehen. Der Code ist in der [Code-Sammlung](#listen-code).

    #### Aufzählungsliste
    1. Aufzählungs-
    3. Liste
        3. Mit
        2. Unterliste
    4. Ganz
    2. Einfach

    #### Listenpunkte
    - Dies ist
        + Unterliste
        * ohne Inhalt
    * eine einfache
    + Liste

    #### Definitionsliste
    Des Weiteren gibt es eine Definitionsliste. Sie wird benutzt, indem der zu definierenden Zeile die nachfolgende Definition mit einem Doppelpunkt (`:`) anfängt.

    Holarse
    : Holarse ist eine Internetseite über Linuxspiele

    Linuxspiele
    : Linuxspiele sind toll

    ### Code

    #### Code im Text
    Unter Linux kommt es öfters vor, dass spezielle Pakete gebraucht werden oder bestimmte Befehle ausgeführt werden müssen. In einer Zeile erreicht man einen Code-Eintrag, indem man das Gewünschte mit dem [Gravis][2] (`` ` ``) einschließt.
    
    Dies ist ein Beispiel für `eingefügten Code`.

    #### Code-Blöcke
    Es kann jedoch auch mal vorkommen, dass mehrer Befehle gebraucht werden. Hierfür eignen sich Code-Blöcke. Diese werden entweder in jeder zeile mit vier Leerzeichen (1 Tab) begonnen oder mit mindestens 3 [Tilden][3] (`~`) der gesamte Block umschlossen. Bei letzterem kann auch einfach eine Sprache definiert werden, indem man den Sprachennamen hinter die Anfangstilden setzt.
    Sowie ein Code-Block in Ruby:

    ~~~ ruby
    def what?
      42
    end
    ~~~

    Der Code ist in der [Code-Sammlung](#code-code)

    ### Links
    Links erstellt man in runden Klammern (`()`). Davor muss der angezeigte Text in eckigen Klammern (`[]`) gesetzt werden: `[Holarse](http://www.holarse-linuxgaming.de/)` ergibt [Holarse][4]. Interne Links werden automatisch verlinkt. Links zu einer [Überschrift](#berschriften) werden so gesetzt: `[Überschrift](#berschriften)` die Sprungmarke in den runden Klammern, die nach einem [Doppelkreuz][1] (`#`) folgt, wird klein geschrieben, Umlaute fallen weg, Leerzeichen werden durch Bindestriche ersetzt.

    ### Bilder
    Bilder sind equivalent zu [Links](#links), nur mit einem vorangestelltem Ausrufezeichen (`!`): `![Logo](http://www.holarse-linuxgaming.de/sites/default/files/cti_flex_logo.png)` ergibt ![Logo](http://www.holarse-linuxgaming.de/sites/default/files/cti_flex_logo.png).
    Bilder sollen nicht für Screenshots genutzt werden. Vielmehr sollen sie zur Verdeutlichung herangezogen werden, z.B. für verschiedene Gegnerklassen oder ähnliches.

    ### Zitate
    Zitate werden wie in E-Mails gehändelt, also wird jeder Zitatzeile ein größer als `>` vorgesesetzt.
    
    > Dieses Zitat wurde mit folgendem Code erstellt: `> Dieses Zitat wurde mit folgendem Code erstellt:`
    
    ### Formatierungen
    
    #### Kusiv
    Um Wörter kusiv zu schreiben, wird der betreffende Teil mit einem [Asterisk][7] (`*`) oder [Unterstrich][8] (`_`) eingegrenzt. Mit dem [Asterisk][7] funktioniert das auch innerhalb eines Wortes.
    
    Die Kombination `_Dies_ ist ein *kursi*ver Text` erzeugt also foglende Formatierung: _Dies_ ist ein *kursi*ver Text.
    
    #### Fett
    Fettschreibung lässt sich genauso wie die [Kursivschreibung](#kursiv) erstellen, mit der Änderung, dass das [Asterisk][7] oder der [Unterstrich][8] in doppelter Ausführung gesetzt wird.
    
    Die Kombination `__Dies__ ist ein **fett**er Text` erzeugt also foglende Formatierung: __Dies__ ist ein **fett**er Text.

    ### Linien
    Horizontale Linien können als Trennzeichen benutzt werden, zum Beispiel um einzelne Serientitel abzugrenzen. Sie werden mit 3 oder mehr `-`, `_` oder `*` erzeugt. Als Beispiel erzeugt `--- ---      - - - -` folgende Linie:

    --- ---      - - - -

    ### Weiterführende Informationen

    - [Kramdown Schnelleinführung][5]
    - [Daring Fireball Markdown: Syntax][6]
    - Musterartikel

    -----

    ### Code-Sammlung

    #### Listen-Code
    ~~~
    1. Aufzählungs-
    3. Liste
        3. Mit
        2. Unterliste
    4. Ganz
    2. Einfach

    - Dies ist
        + Unterliste
        * ohne Inhalt
    * eine einfache
    + Liste

    Holarse
    : Holarse ist eine Internetseite über Linuxspiele

    Linuxspiele
    : Linuxspiele sind toll
    ~~~

    #### Code-Code
    ~~~~~
    Dies ist ein Beispiel für `eingefügten Code`.
    Sowie ein Code-Block in Ruby:

    ~~~ ruby
    def what?
      42
    end
    ~~~
    ~~~~~

    [1]: https://de.wikipedia.org/wiki/Doppelkreuz_%28Schriftzeichen%29
    [2]: https://de.wikipedia.org/wiki/Gravis_%28Typografie%29
    [3]: https://de.wikipedia.org/wiki/Tilde
    [4]: http://www.holarse-linuxgaming.de/
    [5]: http://kramdown.rubyforge.org/quickref.html
    [6]: http://daringfireball.net/projects/markdown/syntax
    [7]: https://de.wikipedia.org/wiki/Sternchen_%28Schriftzeichen%29
    [8]: https://de.wikipedia.org/wiki/Unterstrich

app/views/static_pages/newcontent.html.haml
.row
  .col-md-12
    .panel.panel-red
      .panel-heading
        %h3.panel-title
          = fa_icon "gamepad" do
            Artikel
      .panel-body
        %h4
          Spielbeschreibung, Tool, usw
        %p
          blabla
        %p
          = link_to "Neuer Artikel", new_article_path, class: "btn-u btn-u-red"
          
.row
  .col-md-12
    .panel.panel-blue
      .panel-heading
        %h3.panel-title
          = fa_icon "shoutbox" do
            News
      .panel-body
        %h4
          Neuigkeiten, Spiele-Update, Brandheisse Infos
        %p
          blabla
        %p
          = link_to "Neue News", new_news_path, class: "btn-u btn-u-blue"
          
.row
  .col-md-12
    .panel.panel-green
      .panel-heading
        %h3.panel-title
          = fa_icon "euro" do
            Rabattaktionen
      .panel-body
        %h4
          Vergünstigungen aller Art
        %p
          blabla
        %p
          = link_to "Neue Rabattaktion", new_discount_event_path, class: "btn-u btn-u-green"