config/routes.rb
Holarse::Application.routes.draw do

  get "impressum" => "static_pages#imprint", as: :imprint
  get "intro" => "static_pages#intro", as: :introduction
  get "markdownhelp" => "static_pages#markdownhelp", as: :markdownhelp
  get "newcontent" => "static_pages#newcontent", as: :newcontent

  # api
  get "holarse/api/autolinkable" # erzeugt die internen links auf artikel
  get "holarse/api/discount_count" # zaehlt die rabattaktionen
  post "holarse/api/markup_preview" # ermoeglicht die vorschau von markdown-seiten
  get "holarse/api/minecrafters" # die whitegelisteten minecraft-user
  get "holarse/api/site_statistics" # die holarse-statistik
  get "holarse/api/taglist" # die tagliste je kategorie
  get "holarse/api/mumble" # der mumble-user count
  post "holarse/api/grab_title" # der seitentitel
  get "holarse/api/inbox_count"

  # holarse-services-seiten
  get "holarse/service/index", as: :holarse_service
  get "holarse/service/mumble", as: :holarse_service_mumble
  get "holarse/service/jabber", as: :holarse_service_jabber
  get "holarse/service/gameserver", as: :holarse_service_gameserver
  get "holarse/service/communities", as: :holarse_service_communities

  # die angebotsaktionen
  resources :discount_events do
    resources :comments
  end

  resources :inboxes

  # die suche
  get "search/suggest" => "search#suggest"
  match "search/(:q)" => "search#show", as: :search, via: [:get, :post]
  get "search/tags/:q" => "search#tags", as: :searchtag

  # die entwuerfe
  resources :drafts

  # webseiten resourcen
  resources :users
  resources :news do
    resources :comments
    resources :videos
    resources :history
    resources :news_updates
  end

  resources :articles do
    resources :comments
    resources :videos
    resources :history
  end

  # abwaertskompatibilitaet
  get "wiki/:name", to: redirect("/articles/%{name}")

  # login und sessionverwaltung
  get 'users/new', as: :register
  resource :session, only: [:new, :create, :destroy]
  get 'session/login' => 'sessions#new', as: :login
  get 'session/logout' => 'sessions#destroy', as: :logout

  # einzelseiten
  get "welcome/index"
    
  # shortcuts
  get "videos" => "media#videos"

  # redirects
  get "/redirect/twitter" => redirect("https://twitter.com/#!/holarse"), as: :twitter

  get "/redirect/youtube/:channel" => redirect("https://www.youtube.com/user/%{channel}"), as: :youtube_channel

  get '/redirect/osm/:city' => redirect("http://nominatim.openstreetmap.org/search.php?q=%{city}"), as: :osm

  get '/version/:commitid' => redirect("https://github.com/commel/holarse/commit/%{commitid}"), as: :version
  get '/github'	=> redirect("https://github.com/commel/holarse"), as: :github 
  get '/yt/holarse' => redirect("https://www.youtube.com/user/holarse"), as: :youtube

  # root
  root :to => "welcome#index"
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  before_save :save_revision, on: [:create, :update, :delete]

  # validierungen
  validates_presence_of :title, :content, :user
  validates_uniqueness_of :title

  # referenzen
  belongs_to :user
  has_many :videos, as: :videoable
  has_many :revisions, as: :historical

  has_many :comments, as: :commentable

  belongs_to :project_activity_state

  acts_as_taggable_on :categories, :genres

  searchkick language: "German", word_middle: [:title]

  def search_data
    as_json only: [:title, :alternate_title, :content]
  end

  def should_index?
    enabled
  end

  def self.sk_search(term, limit=100)
    search(term, fields: [{title: :word_middle}, :alternate_title, :content], limit: limit).map(&:decorate)
  end

  def self.autosuggest(term)
    sk_search(term, 5).map { |s|
      {
	"title" => s.title,
	"secondary_title" => s.secondary_title,
	"icon" => s.icon,
	"accuracy" => 0,
	"url" => s.link_to
      }
    }
  end

  def self.title_list
    Article.select(:id, :title, :slug) + Article.select("id, alternate_title as title, slug").where("alternate_title is not null")
  end

  default_scope { where(enabled: true) }

end

app/controllers/articles_controller.rb
# encoding: utf-8
class ArticlesController < DraftableController

  before_filter :require_edit_permissions, :except => [:index, :show]
  before_filter :article_frozen?, only: [:edit, :update]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  add_breadcrumb "Artikel", :articles_path

  def index
    @articles = ArticleDecorator.order('created_at DESC')
    add_breadcrumb "Index", articles_path
  end

  def new
    @article = Article.new(project_activity_state: ProjectActivityState.find_by_code(:active))
    render :edit
  end

  def create
    @article = Article.new(has_role(:admin) ? article_admin_params : article_params)
    @article.user = current_user

    if save_or_draft(@article)
      flash[:success] = "Deine Änderungen wurden angelegt"
      redirect_to @article and return
    else
      flash[:fatal] = "Es gab ein Problem beim Speichern"
      redirect_to :back and return
    end
  end

  def edit
    @article = Article.friendly.find(params[:id])
    add_breadcrumb @article.title, article_path(@article)
  end

  def update
    @article = Article.friendly.find(params[:id])
    @article.user = current_user

    # änderungen am model hinterlegen
    @article.assign_attributes(has_role(:admin) ? article_admin_params : article_params)

    if save_or_draft(@article)
      flash[:success] = "Deine Änderungen wurden gespeichert"
      redirect_to @article and return
    else
      flash[:error] = "Es gab ein Problem beim Speichern"
      redirect_to :back and return
    end
  end

  def destroy
  end

  def show
    @article = Article.friendly.find(params[:id]).decorate
    add_breadcrumb @article.title, article_path(@article)
  end

  private

  def record_not_found
    flash[:warning] = "Der Artikel mit dem Namen #{params[:id]} wurde nicht gefunden. Daher wird eine Suche ausgeführt.\nDu kannst den Artikel aber auch #{view_context.link_to('selbst anlegen', new_article_path, class: "alert-link")}."
    redirect_to search_path(params[:id])
  end

  def article_frozen?
    article = Article.friendly.find(params[:id])
    if article.isfrozen and not has_role(:admin)
      flash[:warning] = "Dieser Artikel wurde von den Administratoren eingeforen und kann nicht bearbeitet werden."
      redirect_to :back and return
    end
  end

  def as_draft?
    params.key? "save-as-draft"
  end

  def require_edit_permissions
    if !is_logged_in?
      flash[:info] = "Bitte #{view_context.link_to('anmelden', login_path, class: "alert-link")} zum Bearbeiten des Artikels."
      # TODO vereinheitlichen DRY
      persist_position self.controller_name, self.action_name, params[:id]
      redirect_to login_path
    end
  end

  def article_params
    params.require(:article).permit(:title, :alternate_title, :content, :unreleased, :releasedate, :category_list, :genre_list, :comment, :project_activity_state_id, :reviseme)
  end

  def article_admin_params
     params.require(:article).permit(:title, :alternate_title, :content, :unreleased, :releasedate, :category_list, :genre_list, :comment, :project_activity_state_id, :reviseme, :hasftp, :isfrozen, :comments_allowed)
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper

  def project_activity_indicator(state, css_classes="")
    res = { "active" => "success", "pending" => "info", "inactive" => "warning", "dead" => "danger" }.fetch(state.code)
    content_tag :span, state.name, class: "label label-#{res} #{css_classes}"
  end

end

app/views/articles/_article.html.haml
%li
  = link_to article.title, article

app/views/articles/_navcontext.html.haml
%li
  = link_to new_article_path do
    = fa_icon "file-text"
    Neuer Artikel
- if @article.present? && !@article.new_record? && current_page?(article_path(@article))
  %li
    = link_to edit_article_path(@article) do
      = fa_icon "edit"
      Bearbeiten
  %li
    = link_to article_history_index_path(@article) do
      = fa_icon :book
      Revisionen
      = content_tag :span, :class => "badge" do
        #{@article.revisions.length}
%li
  = link_to markdownhelp_path, target: "_blank" do
    = fa_icon "info-circle"
    Markdown-Doku

app/views/articles/create.html.haml
%h1 Articles#create
%p Find me in app/views/articles/create.html.haml

app/views/articles/destroy.html.haml
%h1 Articles#destroy
%p Find me in app/views/articles/destroy.html.haml

app/views/articles/edit.html.haml
.col-md-12
  #toggle-edit.pull-right
    = fa_icon "arrows-h"
  .row
    #input.col-md-6
      = semantic_form_for @article do |f|
        = f.inputs 'Inhalt' do
          .form-group
            = f.input :title, input_html: { class: "form-control" }
          .form-group
            = f.input :alternate_title, input_html: { class: "form-control" }
          .form-group
            = f.input :content, as: :text, input_html: { rows: 20, cols: 120, class: "form-control", id: "markup-edit-content" }
          .form-group
            = f.input :project_activity_state, label_method: :name, input_html: { class: "form-control" }
        = f.inputs 'Tags' do
          .form-group
            = f.input :category_list, input_html: { class: "form-control tagsinput", :"data-context" => "cateories" }
          .form-group
            = f.input :genre_list, input_html: { class: "form-control tagsinput", :"data-context" => "genres" }
        = f.inputs 'Konfiguration' do
          .form-group
            = f.input :hasftp, input_html: { class: "form-control" }
          .form-group
            = f.input :reviseme, input_html: { class: "form-control" }
          .form-group
            = f.input :isfrozen, input_html: { class: "form-control" }
          .form-group
            = f.input :comments_allowed, input_html: { class: "form-control" }
        = f.inputs 'Noch nicht erschienen' do
          .form-group
            = f.input :unreleased, input_html: { class: "form-control" }
          .form-group
            = f.input :releasedate, input_html: { class: "form-control" }
        = f.actions do
          .form-group
            = f.action :submit, button_html: { name: "save", class: "btn btn-primary" }
            = f.action :submit, label: "Als Entwurf speichern", button_html: { name: "save-as-draft", class: "btn btn-warning" }

    .col-md-6.hidden-sm.hidden-xs#livepreview
      %p#markuppreviewtext

- if not @article.new_record?
  .row
    .col-md-12
      = semantic_form_for [@article, Video.new] do |f|
        = f.inputs do
          .form-group
            = f.input :url, as: :url, input_html: { class: "form-control" }
        = f.actions do
          .from-group
            = f.action :submit, button_html: { class: "btn btn-primary" }      

app/views/articles/index.html.haml
%h1 Articles#index
%p Find me in app/views/articles/index.html.haml

%ul
  = render @articles

app/views/articles/show.html.haml
#content.content.section.row
  .col-md-8.bg-base.col-lg-8.col-xl-9
    .ribbon.ribbon-highlight
      %ol.breadcrumb.ribbon-inner
        = render_breadcrumbs :tag => :li, :separator => ""
    
    %header.page-header
      .


.container
  .row.blog-page.blog-item
    / left sidebar
    .col-md-9.md-margin-bottom-60
      / blog post
      .blog-margin-bottom-40
        %h2
          = link_to @article.title, @article
          %small
            = @article.secondary_title
          %ul.bxslider
            - (1..10).each do |photo|
              %li
                = link_to "http://lorempixel.com/1024/768/technics/#{photo}", class: "fancybox fancybox.image", :"data-fancybox-group" => "gallery" do
                  = image_tag "http://lorempixel.com/300/180/technics/#{photo}", class: "hover-effect da-img"
            - @article.videos.each do |video|
              %li
                = embed_youtube video.url

      %div
        = @article.content.html_safe
      / end blog post
      
      %hr

      / recent comments
      .media
        %a{:name => "comments"}
        %h3
          Kommentare
        = render @article.comments
      / end recent comments

      .post-comment
        = show_commentbox @article
    
    / end left sidebar

    / right sidebar
    .col-md-3.magazine-page
      / article-infos
      .headline.headline-md
        %h2
          Meta
      %ul.list-unstyled.margin-bottom-30
        %li
          = fa_icon "pencil-square"
          = @article.createdtime
        %li
          = fa_icon "pencil-square-o"
          = @article.changetime
        %li
          = fa_icon "users"
          = @article.authors_list.html_safe
        %li
          = fa_icon "tachometer"
          = @article.project_state
        - if @article.reviseme
          %li
            = fa_icon "ambulance"
            Bitte überarbeite mich!
        - if @article.isfrozen
          %li
            = fa_icon "lock"
            Artikel eingeforen
        - if not @article.comments_allowed
          %li
            = fa_icon "warning"
            Kommentare deaktiviert
      / article tags
      .headline.headline-md
        %h2
          Tags
      %ul.list-unstyled.list-inline.blog-info
        %li
          = fa_icon "tags"
          - @article.tags.each do |tag|
            = link_to tag, searchtag_path(tag)

      / similar articles
      .headline.headline-md
        %h2
          Ähnliche Artikel
      %ul.list-unstyled.blog-tags.margin-bottom-30
        - @article.similar(fields: ["title", "content"]).each do |similar_article|
          %li= link_to similar_article.title, similar_article

app/views/articles/update.html.haml
%h1 Articles#update
%p Find me in app/views/articles/update.html.haml