config/routes.rb
Holarse::Application.routes.draw do

  get "impressum" => "static_pages#imprint", as: :imprint
  get "intro" => "static_pages#intro", as: :introduction
  get "markdownhelp" => "static_pages#markdownhelp", as: :markdownhelp
  get "newcontent" => "static_pages#newcontent", as: :newcontent

  # api
  get "holarse/api/autolinkable" # erzeugt die internen links auf artikel
  get "holarse/api/discount_count" # zaehlt die rabattaktionen
  post "holarse/api/markup_preview" # ermoeglicht die vorschau von markdown-seiten
  get "holarse/api/minecrafters" # die whitegelisteten minecraft-user
  get "holarse/api/site_statistics" # die holarse-statistik
  get "holarse/api/taglist" # die tagliste je kategorie
  get "holarse/api/mumble" # der mumble-user count
  post "holarse/api/grab_title" # der seitentitel
  get "holarse/api/inbox_count"

  # holarse-services-seiten
  get "holarse/service/index", as: :holarse_service
  get "holarse/service/mumble", as: :holarse_service_mumble
  get "holarse/service/jabber", as: :holarse_service_jabber
  get "holarse/service/gameserver", as: :holarse_service_gameserver
  get "holarse/service/communities", as: :holarse_service_communities

  # die angebotsaktionen
  resources :discount_events do
    resources :comments
  end

  resources :inboxes

  # die suche
  get "search/suggest" => "search#suggest"
  match "search/(:q)" => "search#show", as: :search, via: [:get, :post]
  get "search/tags/:q" => "search#tags", as: :searchtag

  # die entwuerfe
  resources :drafts

  # webseiten resourcen
  resources :users
  resources :news do
    resources :comments
    resources :videos
    resources :history
    resources :news_updates
  end

  resources :articles do
    resources :comments
    resources :videos
    resources :history
  end

  # abwaertskompatibilitaet
  get "wiki/:name", to: redirect("/articles/%{name}")

  # login und sessionverwaltung
  get 'users/new', as: :register
  resource :session, only: [:new, :create, :destroy]
  get 'session/login' => 'sessions#new', as: :login
  get 'session/logout' => 'sessions#destroy', as: :logout

  # einzelseiten
  get "welcome/index"
    
  # shortcuts
  get "videos" => "media#videos"

  # redirects
  get "/redirect/twitter" => redirect("https://twitter.com/#!/holarse"), as: :twitter

  get "/redirect/youtube/:channel" => redirect("https://www.youtube.com/user/%{channel}"), as: :youtube_channel

  get '/redirect/osm/:city' => redirect("http://nominatim.openstreetmap.org/search.php?q=%{city}"), as: :osm

  get '/version/:commitid' => redirect("https://github.com/commel/holarse/commit/%{commitid}"), as: :version
  get '/github'	=> redirect("https://github.com/commel/holarse"), as: :github 
  get '/yt/holarse' => redirect("https://www.youtube.com/user/holarse"), as: :youtube

  # root
  root :to => "welcome#index"
  
end

app/models/news_update.rb
class NewsUpdate < ActiveRecord::Base

  default_scope { order('created_at DESC') }

  belongs_to :news
  belongs_to :user

  validates_presence_of :news, :user

end

app/controllers/news_updates_controller.rb
#encoding: utf-8
class NewsUpdatesController < ApplicationController

  add_breadcrumb "News"

  def index
    @news = load_news
    add_breadcrumb @news.title, @news
    add_breadcrumb "Updates"
    add_breadcrumb "Übersicht"
    @news_updates = @news.news_updates.decorate
  end

  def show
    @news = load_news
    add_breadcrumb @news.title, @news
    add_breadcrumb "Updates"
    @news_update = NewsUpdate.find(params[:id]).decorate
    add_breadcrumb @news_update.id
  end

  def update
    @news = load_news
    @news_update = NewsUpdate.find(params[:id])
    @news_update.user = current_user

    @news_update.assign_attributes(news_update_params)

    @news_update.save

    redirect_to @news
  end

  def edit
    @news = load_news
    add_breadcrumb @news.title, @news
    add_breadcrumb "Updates"
    @news_update = NewsUpdate.find(params[:id])
    add_breadcrumb @news_update.id
    add_breadcrumb "Bearbeiten"
  end

  def new
    @news = load_news
    add_breadcrumb @news.title, @news
    add_breadcrumb "Updates"
    add_breadcrumb "Neues Update"
    @news_update = NewsUpdate.new
    render :edit
  end

  def create
    @news = load_news
    @news_update = NewsUpdate.new(news_update_params)

    @news_update.user = current_user
    @news_update.news = @news

    if @news_update.save
      flash[:success] = "Das Update wurde angehangen"
      redirect_to @news
    else
      flash[:fatal] = "Das Update konnte nicht gespeichert werden."
      redirect_to :back
    end
  end

  private

  def news_update_params
    params.require(:news_update).permit(:content)
  end

  def load_news
    News.friendly.find(params[:news_id]).decorate
  end

end

app/views/news_updates/_navcontext.html.haml
%li
  = link_to new_news_news_update_path(@news) do
    = fa_icon "bullhorn"
    Neues Update
- if @news_update.present? && !@news_update.new_record?
  %li
    = link_to edit_news_news_update_path(@news, @news_update) do
      = fa_icon "edit"
      Bearbeiten

app/views/news_updates/_news_update.html.haml
.tag-box.tag-box-v2
  %h2
    Update
    = news_update.changetime
    von
    = news_update.author
  %p
    = news_update.content

app/views/news_updates/edit.html.haml
= semantic_form_for [@news, @news_update] do |f|
  = f.inputs do
    .form-group
      = f.input :content, as: :text, input_html: { class: "form-control" }
  = f.action :submit, as: :button, button_html: { class: "btn btn-primary" }

app/views/news_updates/index.html.haml
.col-md-12
  .panel.panel-red.margin-bottom-40
    .panel-heading
      %h3.panel-title
        = fa_icon ""
        News-Updates für 
        = link_to @news.title, @news
    .panel-body
      %p
        Hier können die News-Updates zu einer News verfasst werden.
    %table.table.table-hover.sortable
      %thead
        %tr
          %th
            ID
          %th
            Erstelldatum
          %th
            Inhalt
          %th
            Bearbeiten
      %thead
        - @news_updates.each do |news_update|
          %tr
            %td
              = link_to news_update.id, news_news_update_path(@news, news_update)
            %td
              = l(news_update.created_at)
            %td
              = news_update.content
            %td
              = link_to edit_news_news_update_path(@news, news_update) do
                = fa_icon "edit"

app/views/news_updates/show.html.haml
%h2
  News-Update für
  = link_to @news.title, @news
= render @news_update