config/routes.rb
Holarse::Application.routes.draw do

  get "impressum" => "static_pages#imprint", as: :imprint
  get "intro" => "static_pages#intro", as: :introduction
  get "markdownhelp" => "static_pages#markdownhelp", as: :markdownhelp
  get "newcontent" => "static_pages#newcontent", as: :newcontent

  # api
  get "holarse/api/autolinkable" # erzeugt die internen links auf artikel
  get "holarse/api/discount_count" # zaehlt die rabattaktionen
  post "holarse/api/markup_preview" # ermoeglicht die vorschau von markdown-seiten
  get "holarse/api/minecrafters" # die whitegelisteten minecraft-user
  get "holarse/api/site_statistics" # die holarse-statistik
  get "holarse/api/taglist" # die tagliste je kategorie
  get "holarse/api/mumble" # der mumble-user count
  post "holarse/api/grab_title" # der seitentitel
  get "holarse/api/inbox_count"

  # holarse-services-seiten
  get "holarse/service/index", as: :holarse_service
  get "holarse/service/mumble", as: :holarse_service_mumble
  get "holarse/service/jabber", as: :holarse_service_jabber
  get "holarse/service/gameserver", as: :holarse_service_gameserver
  get "holarse/service/communities", as: :holarse_service_communities

  # die angebotsaktionen
  resources :discount_events do
    resources :comments
  end

  resources :inboxes

  # die suche
  get "search/suggest" => "search#suggest"
  match "search/(:q)" => "search#show", as: :search, via: [:get, :post]
  get "search/tags/:q" => "search#tags", as: :searchtag

  # die entwuerfe
  resources :drafts

  # webseiten resourcen
  resources :users
  resources :news do
    resources :comments
    resources :videos
    resources :history
    resources :news_updates
  end

  resources :articles do
    resources :comments
    resources :videos
    resources :history
  end

  # abwaertskompatibilitaet
  get "wiki/:name", to: redirect("/articles/%{name}")

  # login und sessionverwaltung
  get 'users/new', as: :register
  resource :session, only: [:new, :create, :destroy]
  get 'session/login' => 'sessions#new', as: :login
  get 'session/logout' => 'sessions#destroy', as: :logout

  # einzelseiten
  get "welcome/index"
    
  # shortcuts
  get "videos" => "media#videos"

  # redirects
  get "/redirect/twitter" => redirect("https://twitter.com/#!/holarse"), as: :twitter

  get "/redirect/youtube/:channel" => redirect("https://www.youtube.com/user/%{channel}"), as: :youtube_channel

  get '/redirect/osm/:city' => redirect("http://nominatim.openstreetmap.org/search.php?q=%{city}"), as: :osm

  get '/version/:commitid' => redirect("https://github.com/commel/holarse/commit/%{commitid}"), as: :version
  get '/github'	=> redirect("https://github.com/commel/holarse"), as: :github 
  get '/yt/holarse' => redirect("https://www.youtube.com/user/holarse"), as: :youtube

  # root
  root :to => "welcome#index"
  
end

app/controllers/holarse/api_controller.rb
class Holarse::ApiController < ApplicationController

  skip_before_filter :verify_authenticity_token, only: [:markup_preview, :site_statistics]

  respond_to :json

  def grab_title
    raise "no url given" if params[:url].empty?

    title = Mechanize.new.get(params[:url]).title
    Rails.logger.debug("Grabbing title for #{params[:url]} => #{title}")
    render :text => {
      title: title
    }.to_json
  end

  def markup_preview
    render :text => Holarse::Markup.render( params[:content] )
  end

  def minecrafters
    render :text => User.minecrafters.to_json(only: :minecraft_username)    
  end

  def site_statistics
    stats = {
      "stats" => [
	{ "name" => "Artikel", 
	  "icon" => "fa fa-gamepad",
	  "count" => Article.count.to_json 
	},
	{ "name" => "Kommentare", 
	  "icon" => "fa fa-comments",
	  "count" => Comment.count.to_json 
	},
	{ "name" => "News", 
	  "icon" => "fa fa-bell",
	  "count" => News.count.to_json 
	},
	{ "name" => "Benutzer", 
	  "icon" => "fa fa-group",
	  "count" => User.count.to_json 
	}
    ]}

    render :text => stats.to_json
  end

  def taglist
    render :text => taglist_by_context(params[:context], params[:term])
  end

  def discount_count
    render text: cached_model_count(DiscountEvent).to_json
  end

  def inbox_count
    render text: cached_model_count(Inbox).to_json
  end

  def mumble
    count = Rails.cache.fetch "mumble-count", expires_in: 1.minute do
      {
	url: Holarse::Application.config.mumbleurl,
	count: Holarse::Mumble.count
      }
    end

    render :text => count.to_json
  end

  protected

  def cached_model_count(model)
    count = Rails.cache.fetch "#{model.to_s.downcase}-count", expires_in: 1.minute do
      {
	count: model.all.count
      }
    end
  end

  def taglist_by_context(context, searchword="")
    ActsAsTaggableOn::Tagging.joins("inner join tags on tags.id = tag_id").where(context: context).where("tags.name like ?", "%#{searchword}%").select("tags.name").map(&:name).uniq
  end

  def update_user_activity
    # soll nicht als aktivitaet zaehlen, daher wird
    # die methode hier ueberschrieben
  end

end

app/controllers/holarse/service_controller.rb
# encoding: utf-8
class Holarse::ServiceController < ApplicationController

  add_breadcrumb "Holarse"
  add_breadcrumb "Services"

  def index
    add_breadcrumb "Übersicht"
  end

  def mumble
    add_breadcrumb "Mumble"
  end

  def jabber
    add_breadcrumb "IRC und Jabber"
  end

  def gameserver
    add_breadcrumb "Gameserver"
  end

  def communities
    add_breadcrumb "Communities"
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  
  respond_to :json
  
  def minecraft
    @users = User.all_of(:minecraft_active => true, :minecraft_username.ne => "")
    respond_to do |format|
      format.json { render :json => @users.to_json(:only => [:minecraft_username]) }
    end    
  end
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/holarse/service/communities.html.haml
.page-header
  %h1
    Communities
    %small
      Holarse im Web

Ihr könnt Holarse an vielen Stellen im Netz finden. Wir bevorzugen jedoch, wenn möglich, freie Alternativen.

.list-group
  = link_to "Desura",   "http://www.desura.com/groups/holarse-linuxgaming", class: "list-group-item"
  = link_to "Steam",    "http://steamcommunity.com/groups/holarse", class: "list-group-item"
  = link_to "Diaspora", "https://pod.geraspora.de/u/holarse", class: "list-group-item"

app/views/holarse/service/gameserver.html.haml
%h1 HolarseService#minecraft
%p Find me in app/views/holarse_service/minecraft.html.haml

app/views/holarse/service/index.html.haml
.page-header
  %h1
    Holarse-Services
    %small
      Tools f&uuml;r Linuxgamer

%p
  Holarse informiert nicht nur rund um Linux-Spiele. Wir wollen auch die Linuxspieler-Community n&auml;her zusammenbringen. Daher bieten wir hier euch
  jedemenge n&uuml;tzlicher Dienste an, die ihr zum Spielen unter Linux mit anderen Linuxspielern zusammen nutzen k&ouml;nnt.

%p
  %ul
    %li
      = link_to "Mumble-Server", holarse_service_mumble_path
    %li
      = link_to "Jabber-Server", holarse_service_jabber_path
    %li
      = link_to "Gameserver", holarse_service_gameserver_path

%p
  Auf Anfrage stellen wir auch gerne andere Dienste oder Gameserver bereit. Sprecht uns einfach an.

app/views/holarse/service/jabber.html.haml
.page-header
  %h1
    IRC und Jabber
    %small
      Quatschen mit Linuxgamern

= semantic_form_for 'irc', :url => Holarse::Application.config.webchaturl do |f|
  = f.actions do
    = f.action :submit, button_html: { class: "btn-u btn-block" }, label: "IRC-Webchat starten"

:markdown
  
  ### Jabber
  
  Holarse bietet Euch einen Jabber-Server. Registrierte Benutzer können sich einfach bei ihm registrieren.
  
  #### Serverdaten
  
  Adresse:
  : `holarse-linuxgaming.de`
  
  ### IRC
  
  #### Generelles
  Im IRC wird die ständige Möglichkeit zum Austausch geboten. Ihr könnt über den [Webchat](#webchat) oder über Euren [eigenen Client](#serverdaten) mit uns reden.
  
  #### Webchat
  Zum Webchat gelangt Ihr über den Button oben. Sucht euch einen Nick aus und treten dem Kanal einfach bei.
  
  ##### Hinweis für alle IRC-Neulinge:
  
  Wenn Ihr eine Frage stellt, erwartet bitte nicht, innerhalb von fünf Minuten eine Antwort zu erhalten. Geduldet Euch bitte und bleibt ein paar Stunden online. Viele im Holarse-Channel schauen nur sporadisch rein und werden erst nach einiger Zeit antworten. Sollte es trotzdem keine Antwort geben versucht es einfach später noch einmal. Geholfen wird auf jeden Fall.
  
  #### Serverdaten
  
  Adresse:
  : `irc.oftc.net`
  
  Port:
  : `6667`
  
  Raum:
  : `#holarse-gaming`

app/views/holarse/service/mumble.html.haml
.page-header
  %h1
    Mumble
    %small
      Quatschen mit Linuxgamern in Live

= semantic_form_for 'mumble', :url => Holarse::Application.config.mumbleurl do |f|
  = f.actions do
    = f.action :submit, button_html: { class: "btn-u btn-block" }, label: "Mumble beitreten"

:markdown
  ### Serverinformationen
  Wir haben für Euch einen aktuellen Mumble VoIP-Server bereitstehen. Klickt einfach oben auf den Button und öffnet den Link mit Mumble, oder betretet den Server manuell über die [Serverdaten](#Serverdaten).
  
  #### Wichtiges:
  * Anders als bei TeamSpeak händelt jeder Nutzer nur den eigenen Ton. Andere Personen können nicht einzeln beeinflusst werden. Umso wichtiger ist es die Einstellungen an Eure Lautsprecher und Euer Mikrofon anzupassen. Folgt hierzu am Besten dem Audioassistenten von Mumble – zu finden unter *Konfiguration*.
  
  * Achtet darauf, dass Ihr die aktuelle Version benutzt und den Opus-Codec installiert habt. Ansonsten kann es vorkommen, dass Ihr andere Teilnehmer weder hört, noch sprechen seht.
  
  ### Serverdaten
  Adresse:
  : `holarse-linuxgaming.de`
  
  Passwort:
  : `holarse`